#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KOAFORWPF
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="KUAFOR")]
	public partial class KuaforDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCALISAN(CALISAN instance);
    partial void UpdateCALISAN(CALISAN instance);
    partial void DeleteCALISAN(CALISAN instance);
    partial void InsertCALISANURUN(CALISANURUN instance);
    partial void UpdateCALISANURUN(CALISANURUN instance);
    partial void DeleteCALISANURUN(CALISANURUN instance);
    partial void InsertURUN(URUN instance);
    partial void UpdateURUN(URUN instance);
    partial void DeleteURUN(URUN instance);
    #endregion
		
		public KuaforDataDataContext() : 
				base(global::KOAFORWPF.Properties.Settings.Default.KUAFORConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KuaforDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KuaforDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KuaforDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KuaforDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CALISAN> CALISANs
		{
			get
			{
				return this.GetTable<CALISAN>();
			}
		}
		
		public System.Data.Linq.Table<CALISANURUN> CALISANURUNs
		{
			get
			{
				return this.GetTable<CALISANURUN>();
			}
		}
		
		public System.Data.Linq.Table<URUN> URUNs
		{
			get
			{
				return this.GetTable<URUN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CALISAN")]
	public partial class CALISAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CalisanID;
		
		private string _Isim;
		
		private string _Soyisim;
		
		private System.DateTime _Isbaslangic;
		
		private char _Cinsiyet;
		
		private EntitySet<CALISANURUN> _CALISANURUNs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCalisanIDChanging(int value);
    partial void OnCalisanIDChanged();
    partial void OnIsimChanging(string value);
    partial void OnIsimChanged();
    partial void OnSoyisimChanging(string value);
    partial void OnSoyisimChanged();
    partial void OnIsbaslangicChanging(System.DateTime value);
    partial void OnIsbaslangicChanged();
    partial void OnCinsiyetChanging(char value);
    partial void OnCinsiyetChanged();
    #endregion
		
		public CALISAN()
		{
			this._CALISANURUNs = new EntitySet<CALISANURUN>(new Action<CALISANURUN>(this.attach_CALISANURUNs), new Action<CALISANURUN>(this.detach_CALISANURUNs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CalisanID
		{
			get
			{
				return this._CalisanID;
			}
			set
			{
				if ((this._CalisanID != value))
				{
					this.OnCalisanIDChanging(value);
					this.SendPropertyChanging();
					this._CalisanID = value;
					this.SendPropertyChanged("CalisanID");
					this.OnCalisanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isim", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Isim
		{
			get
			{
				return this._Isim;
			}
			set
			{
				if ((this._Isim != value))
				{
					this.OnIsimChanging(value);
					this.SendPropertyChanging();
					this._Isim = value;
					this.SendPropertyChanged("Isim");
					this.OnIsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soyisim", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string Soyisim
		{
			get
			{
				return this._Soyisim;
			}
			set
			{
				if ((this._Soyisim != value))
				{
					this.OnSoyisimChanging(value);
					this.SendPropertyChanging();
					this._Soyisim = value;
					this.SendPropertyChanged("Soyisim");
					this.OnSoyisimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Isbaslangic", DbType="Date NOT NULL")]
		public System.DateTime Isbaslangic
		{
			get
			{
				return this._Isbaslangic;
			}
			set
			{
				if ((this._Isbaslangic != value))
				{
					this.OnIsbaslangicChanging(value);
					this.SendPropertyChanging();
					this._Isbaslangic = value;
					this.SendPropertyChanged("Isbaslangic");
					this.OnIsbaslangicChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="NChar(1) NOT NULL")]
		public char Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this.OnCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyet = value;
					this.SendPropertyChanged("Cinsiyet");
					this.OnCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CALISAN_CALISANURUN", Storage="_CALISANURUNs", ThisKey="CalisanID", OtherKey="CalisanID")]
		public EntitySet<CALISANURUN> CALISANURUNs
		{
			get
			{
				return this._CALISANURUNs;
			}
			set
			{
				this._CALISANURUNs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CALISANURUNs(CALISANURUN entity)
		{
			this.SendPropertyChanging();
			entity.CALISAN = this;
		}
		
		private void detach_CALISANURUNs(CALISANURUN entity)
		{
			this.SendPropertyChanging();
			entity.CALISAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CALISANURUN")]
	public partial class CALISANURUN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _CalisanUrunID;
		
		private int _CalisanID;
		
		private int _UrunID;
		
		private System.DateTime _Tarih;
		
		private EntityRef<CALISAN> _CALISAN;
		
		private EntityRef<URUN> _URUN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCalisanUrunIDChanging(int value);
    partial void OnCalisanUrunIDChanged();
    partial void OnCalisanIDChanging(int value);
    partial void OnCalisanIDChanged();
    partial void OnUrunIDChanging(int value);
    partial void OnUrunIDChanged();
    partial void OnTarihChanging(System.DateTime value);
    partial void OnTarihChanged();
    #endregion
		
		public CALISANURUN()
		{
			this._CALISAN = default(EntityRef<CALISAN>);
			this._URUN = default(EntityRef<URUN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanUrunID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int CalisanUrunID
		{
			get
			{
				return this._CalisanUrunID;
			}
			set
			{
				if ((this._CalisanUrunID != value))
				{
					this.OnCalisanUrunIDChanging(value);
					this.SendPropertyChanging();
					this._CalisanUrunID = value;
					this.SendPropertyChanged("CalisanUrunID");
					this.OnCalisanUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CalisanID", DbType="Int NOT NULL")]
		public int CalisanID
		{
			get
			{
				return this._CalisanID;
			}
			set
			{
				if ((this._CalisanID != value))
				{
					if (this._CALISAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCalisanIDChanging(value);
					this.SendPropertyChanging();
					this._CalisanID = value;
					this.SendPropertyChanged("CalisanID");
					this.OnCalisanIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", DbType="Int NOT NULL")]
		public int UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					if (this._URUN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tarih", DbType="Date NOT NULL")]
		public System.DateTime Tarih
		{
			get
			{
				return this._Tarih;
			}
			set
			{
				if ((this._Tarih != value))
				{
					this.OnTarihChanging(value);
					this.SendPropertyChanging();
					this._Tarih = value;
					this.SendPropertyChanged("Tarih");
					this.OnTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CALISAN_CALISANURUN", Storage="_CALISAN", ThisKey="CalisanID", OtherKey="CalisanID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public CALISAN CALISAN
		{
			get
			{
				return this._CALISAN.Entity;
			}
			set
			{
				CALISAN previousValue = this._CALISAN.Entity;
				if (((previousValue != value) 
							|| (this._CALISAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CALISAN.Entity = null;
						previousValue.CALISANURUNs.Remove(this);
					}
					this._CALISAN.Entity = value;
					if ((value != null))
					{
						value.CALISANURUNs.Add(this);
						this._CalisanID = value.CalisanID;
					}
					else
					{
						this._CalisanID = default(int);
					}
					this.SendPropertyChanged("CALISAN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="URUN_CALISANURUN", Storage="_URUN", ThisKey="UrunID", OtherKey="UrunID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public URUN URUN
		{
			get
			{
				return this._URUN.Entity;
			}
			set
			{
				URUN previousValue = this._URUN.Entity;
				if (((previousValue != value) 
							|| (this._URUN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._URUN.Entity = null;
						previousValue.CALISANURUNs.Remove(this);
					}
					this._URUN.Entity = value;
					if ((value != null))
					{
						value.CALISANURUNs.Add(this);
						this._UrunID = value.UrunID;
					}
					else
					{
						this._UrunID = default(int);
					}
					this.SendPropertyChanged("URUN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URUN")]
	public partial class URUN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UrunID;
		
		private string _UrunAd;
		
		private double _UrunFiyat;
		
		private EntitySet<CALISANURUN> _CALISANURUNs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUrunIDChanging(int value);
    partial void OnUrunIDChanged();
    partial void OnUrunAdChanging(string value);
    partial void OnUrunAdChanged();
    partial void OnUrunFiyatChanging(double value);
    partial void OnUrunFiyatChanged();
    #endregion
		
		public URUN()
		{
			this._CALISANURUNs = new EntitySet<CALISANURUN>(new Action<CALISANURUN>(this.attach_CALISANURUNs), new Action<CALISANURUN>(this.detach_CALISANURUNs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UrunID
		{
			get
			{
				return this._UrunID;
			}
			set
			{
				if ((this._UrunID != value))
				{
					this.OnUrunIDChanging(value);
					this.SendPropertyChanging();
					this._UrunID = value;
					this.SendPropertyChanged("UrunID");
					this.OnUrunIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunAd", DbType="NVarChar(25) NOT NULL", CanBeNull=false)]
		public string UrunAd
		{
			get
			{
				return this._UrunAd;
			}
			set
			{
				if ((this._UrunAd != value))
				{
					this.OnUrunAdChanging(value);
					this.SendPropertyChanging();
					this._UrunAd = value;
					this.SendPropertyChanged("UrunAd");
					this.OnUrunAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrunFiyat", DbType="Float NOT NULL")]
		public double UrunFiyat
		{
			get
			{
				return this._UrunFiyat;
			}
			set
			{
				if ((this._UrunFiyat != value))
				{
					this.OnUrunFiyatChanging(value);
					this.SendPropertyChanging();
					this._UrunFiyat = value;
					this.SendPropertyChanged("UrunFiyat");
					this.OnUrunFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="URUN_CALISANURUN", Storage="_CALISANURUNs", ThisKey="UrunID", OtherKey="UrunID")]
		public EntitySet<CALISANURUN> CALISANURUNs
		{
			get
			{
				return this._CALISANURUNs;
			}
			set
			{
				this._CALISANURUNs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CALISANURUNs(CALISANURUN entity)
		{
			this.SendPropertyChanging();
			entity.URUN = this;
		}
		
		private void detach_CALISANURUNs(CALISANURUN entity)
		{
			this.SendPropertyChanging();
			entity.URUN = null;
		}
	}
}
#pragma warning restore 1591
